{% set name = "pyQParamWidget" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyQParamWidget-{{ version }}.tar.gz
  sha256: 51aa457b82f9bb038998788b9c3780c21a07c95f15d128f4b4ab0c841811e4b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - pyqt =5
    - setuptools >=64.0
    - setuptools-scm >=8.0
  run:
    - python >=3.10
    - pyqt =5

test:
  imports:
    - pyQParamWidget
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://prjemian.github.io/pyQParamWidget/
  license_file: pyQParamWidget/LICENSE.txt
  license: CC-BY-4.0
  summary: A PyQt5 editor (QWidget) and tree (QDialog) to edit application parameters.

extra:
  recipe-maintainers:
    - prjemian
